### ISSUE TITLE
Please do not include your private input in the repo

### ISSUE THREAD

**Issue by RaczeQ** [m-chojnacki/AdventOfCode#1]
https://www.reddit.com/r/adventofcode/comments/k99rod/sharing_input_data_were_we_requested_not_to/

Although purging old repos isn't expected by the users, the author asks not to publish your private input in any form.

**Comment by m-chojnacki** [comment]
Do you know if example input from the puzzle itself is also considered "private input"?
I might consider amending my commits to remove input files.

**Comment by RaczeQ** [comment]
Example input is publicly available AFAIK. Problem is when someone tries to scrap many private inputs and reverse-engineer the puzzle.

**Comment by m-chojnacki** [comment]
I have rewritten Git history not to include private inputs. Thanks for your feedback. I consider this issue closed.
